# Generated by Django 5.0.3 on 2024-03-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('acronym', models.CharField(max_length=10)),
                ('deadline_in_days', models.IntegerField()),
                ('general_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clinic_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratory_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(choices=[('1M', '1 Mes'), ('2M', '2 Meses'), ('3M', '3 Meses'), ('4M', '4 Meses'), ('5M', '5 Meses'), ('6M', '6 Meses'), ('7M', '7 Meses'), ('8M', '8 Meses'), ('9M', '9 Meses'), ('10M', '10 Meses'), ('11M', '11 Meses'), ('1A', '1 Ano'), ('1A1M', '1 Ano e 1 Mês'), ('1A2M', '1 Ano e 2 Meses'), ('1A3M', '1 Ano e 3 Meses'), ('1A4M', '1 Ano e 4 Meses'), ('1A5M', '1 Ano e 5 Meses'), ('1A6M', '1 Ano e 6 Meses'), ('1A7M', '1 Ano e 7 Meses'), ('1A8M', '1 Ano e 8 Meses'), ('1A9M', '1 Ano e 9 Meses'), ('1A10M', '1 Ano e 10 Meses'), ('1A11M', '1 Ano e 11 Meses'), ('2A', '2 Anos')], max_length=10)),
                ('owner', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.customer')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedure')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.race')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.specie')),
            ],
        ),
    ]
