# Generated by Django 5.0.3 on 2024-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='gender',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='payment',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=30),
        ),
    ]
