# Generated by Django 5.0.3 on 2024-03-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_gender_alter_exam_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='observation',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
