# Generated by Django 5.0.3 on 2024-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_age_alter_exam_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
