# Generated by Django 5.0.3 on 2024-03-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
