# Generated by Django 5.0.3 on 2024-03-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cod_exam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='days_elapsed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='deadline_to_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.customer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.procedure'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.race'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.specie'),
        ),
    ]
