# Generated by Django 5.0.3 on 2024-04-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
