# Generated by Django 5.0.3 on 2024-04-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_deleted_at_exam_restored_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.responsible'),
        ),
    ]
